apiVersion: v1
kind: Service
metadata:
  name: after-dark-service
  labels:
    app: after-dark-service
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: after-dark-nginx
    tier: frontend
